ovotech/circleci-orbs

.circleci/config.yml, clair-scanner/README.md, clair-scanner/orb.yml, clair-scanner/scan.sh
This adds a severity_threshold parameter which sets the threshold above which discovered vulnerabilities will fail the build.
=> Add severity_threshold parameter for clair_scanner orb 

clair-scanner/README.md, clair-scanner/orb.yml, clair-scanner/scan.sh
We're running clair-scanning on a set of images and want to do some post-processing (i.e. parsing and communicating the results). So it would be helpful if failing the job is optional.
=> Add parameter for controlling the exit code

terraform/orb.yml, terraform/put_plan.py
Prevent CircleCI from running the orb if bash isn't in the image.
Don't fail if a build is for a branch with no PR.
=> Add better error messages

terraform/apply.sh, terraform/check.sh, terraform/executor/Dockerfile, terraform/init.sh, terraform/plan.sh
Add tfmask to the default executor, and use it to mask output from plan and apply.
The default resource mask pattern is extended to include kubernetes_secret and acme_certificate resources.
=> Mask secrets

terraform/README.md, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12, terraform/init.sh, terraform/orb.yml
Adds Aiven's terraform provider to the terraform executors.
When using the default or terraform-0_11 executors, OVO's 
`terraform-provider-aiven` is available at version `0.0.1`.
To use Aiven's `terraform-provider-aiven` set the AIVEN_PROVIDER 
environment variable and set a version equal or greater than `1.0.0` in 
the provider configuration.
When using the terraform-0_12 executor Aiven's `terraform-provider-aiven` is
always available. (And OVO's is not).
This also adds a version command for testing, which may or may not be useful in the future. I've left it undocumented until I decide.
=> Add Aiven's terraform provider

terraform/executor/Dockerfile-0.12
This is newer than 0.12.2. It allows 0.12.3 state files to be read.
=> Update to Terraform 0.12.3

.circleci/config.yml, clair-scanner/version.txt, terraform/version.txt
This allows controlling when orbs get published, and at what versions.
=> If a specific orb version file exists, use it

clair-scanner/CHANGELOG.md, clair-scanner/README.md, clair-scanner/orb.yml, clair-scanner/orb_version.txt, clair-scanner/scan.sh
fixes #48 
tested with the following:
```yaml
...
...
save_images:
executor: clair_scanner/default
steps:
- setup_remote_docker
- run: |
mkdir /docker-tars
docker pull debian:buster
docker save -o /docker-tars/debian.tar debian:buster
- persist_to_workspace:
root: /
paths:
- docker-tars
scan_loaded_images:
executor: clair_scanner/default
steps:
- attach_workspace:
at: /tmp/workspace
- clair_scanner/scan:
docker_tar_dir: /tmp/workspace/docker-tars
scan_no_images:
executor: clair_scanner/default
steps:
- clair_scanner/scan
workflows:
test:
jobs:
- save_images
- scan_loaded_images:
requires:
- save_images
- scan_no_images
```
`scan_loaded_images` scans debian:buster as expected.
`scan_no_images` fails as expected with:
```
image_file or image parameters or docker tarballs must be present …
```
=> Add docker load func

terraform/cmp.py, tools/include.py
In some environments (with odd locales) `open()` fails unless encoding is specified. Refer to https://github.com/RGF-team/rgf/issues/65, https://github.com/henry0312/pytest-codestyle/pull/34.
Please consider marking this PR with `orbtoberfest` label: https://hacktoberfest.circleci.com/#hacktoberfestOnCircleCI. Thanks a lot!
=> open files with utf-8 in python scripts

tools/orb_stats.py
Outputs the stats in a form datadog can scrape from cloudwatch
Results can be seen here: https://app.datadoghq.com/dashboard/p5m-jsn-5uu/circleci-orb-stats?from_ts=1571562963944&live=true&to_ts=1574154963944
=> Add script to gather orb usage statistics

rac-gcp-deploy/orb.yml
With newer versions of sbt, it uses coursier for dependency resolution. This PR aims to store coursier cache between jobs.
The issue was discovered after updating sbt version to `1.3.4`.
Sbt issue https://github.com/sbt/sbt/issues/5142
Suggested settings https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
=> clean cached directories

rac-gcp-deploy/executor/Dockerfile, rac-gcp-deploy/orb.yml
Change to run `snyk monitor` at the end of the `release` step.
When merged, this will automatically enable Snyk to be run on the next release of our projects (since we depend on the latest `1.x` version of the orb in the projects).
Snyk has their own [orb](https://circleci.com/orbs/registry/orb/snyk/snyk), but since  CircleCI doesn't support using multiple orbs, we've extracted the necessary functionality from the Snyk orb to our own orb.
In order to keep things simple, I've opted to exclude some changes:
- run `snyk monitor` on deploy and have a separate snyk project per environment,
- run `snyk test` on pull requests and comment on the pull request with the output.
Still left to be done:
this is using a service account, and the key is stored in 1Password
=> Add initial snyk support in rac-gcp-deploy

aws-rotate-keys/orb.yml
Avoiding printing AccessKeyId to std out in aws-rotate-keys orb.
=> aws-rotate-keys: avoid printing AccessKeyId to std out

.circleci/config.yml, README.md, aws-rotate-keys/README.md, aws-rotate-keys/executor/Dockerfile, aws-rotate-keys/orb.yml
The aws-rotate-keys repo did not exist in dockerhub
* Modify circleci config to make publishing to dockerhub optional
* Update aws-rotate-keys to use public images maintained by circleci
* Update the readme (added a badge for flair)
=> fix aws-rotate-keys

aws-rotate-keys/README.md, aws-rotate-keys/orb.yml
https://github.com/ovotech/circleci-orbs/pull/115 was supposed to just update the image being used, but it actually modified the behavior
a new feature "use << parameters.aws-secret-access-key-var >> as access credentials" does not work, because you run afoul of interpolation (which users may well want to use)
it was a misguided feature anyway so that is removed, the feature rolled back, the behavior is as before
changes in this PR:
- Stop passing strings to aws-cli/setup when it expects the circleci type `env_var_name`     
- Pin the version of the orb that is a dependency, to prevent surprises in the future
=> Changes for interpolation of var names in aws rotate keys

terraform/executor/Dockerfile-0.11
in the 0.11 dockerfile we just grab the latest:
```
RUN git clone https://github.com/cloudposse/tfmask.git
RUN cd tfmask && make && make go/build
```
when my branch was merged into [cloudposse/tfmask](https://github.com/cloudposse/tfmask), the cloudposse wanted the default terraform version to be switched to 0.12. So this change is just to ensure future builds of the 0.11 image has the `TFENV` env var set.
=> Add TFENV override of 0.11 to tfmask

clair-scanner/scan.sh
Removes the `-x` command line option for `clair-scanner`. This is not one of the options documented at https://github.com/arminc/clair-scanner/blob/master/README.md. Testing locally confirms this resolves the error in issue #89.
Output before fix:
```
latest: Pulling from repo
Digest: sha256:--->8---
Status: Image is up to date for image:latest
Error: incorrect usage
Usage: clair-scanner [OPTIONS] IMAGE
Scan local Docker images for vulnerabilities with Clair
Arguments:
IMAGE=""     Name of the Docker image to scan
Options:
-w, --whitelist=""                    Path to the whitelist file
-t, --threshold="Unknown"             CVE severity threshold. Valid values; 'Defcon1', 'Critical', 'High', 'Medium', 'Low', 'Negligible', 'Unknown'
-c, --clair="http://127.0.0.1:6060"   Clair URL …
```
=> Fixes ovotech/circleci-orbs#89

terraform/CHANGELOG.md, terraform/orb_version.txt
https://circleci.com/orbs/registry/orb/ovotech/terraform#executors-terraform-0_12 is still showing an old image, hence I believe we need to release this
=> Release terraform 1.6.6

.circleci/config.yml, README.md, tools-install/README.md, tools-install/orb.yaml
Often you require some extra tools, not included in CircleCI images, but would like to
avoid overhead of managing your custom build image.
Often tools are distributed as an archive with a statically linked executable file in it,
This orb makes it easy to download, unpack such archives and make executable inside
available in the PATH.
=> Add tools-install orb

.circleci/config.yml, README.md, with-git-deploy-key/README.md, with-git-deploy-key/orb.yml
Sometimes you need to execute git operations on another private repository. When accessing github over SSH, git uses first available key, which is usually the key for your "main" repository, and that key is a [Github deploy key](https://developer.github.com/v3/guides/managing-deploy-keys/). This key is accepted by SSH, so SSH stops trying other keys found in ssh-agent, but rejected by Github auth as not having sufficient permissions for another repository.
This orb provides a command, which configures Git to use specific key found in ssh-agent. Key is  dentified by a fingerprint and needs to be present in the agent already. On a CircleCI you can add more keys to the ssh-agent by creating aditional SSH keys in the project settings.
=> with-git-deploy-key orb

terraform/README.md
Considered just adding the stable repo permanently but seems cleaner to stick with the official approach of not including any repositories by default and allow users to set their own repositories. 
Interestingly this issue only shows up when adding or updating charts through terraform. Non-modified charts plan just fine without any repo present.
=> Updated README to include a note on helm3 usage

terraform/README.md, terraform/init.sh, terraform/set_plan_args.sh
Backwards compatible change to search for backend config file relative to module path
=> Terraform: search for backend-config and var-file in module path too

aws-rotate-keys/README.md
the settings page is now hidden by CircleCI but credentials set there can conflict with the values rotated by this Orb.
=> Add a note to check old aws credentials.

terraform/CHANGELOG.md, terraform/apply.sh, terraform/check.sh, terraform/delete_workspace.sh, terraform/destroy.sh, terraform/init.sh, terraform/new_workspace.sh, terraform/orb_version.txt, terraform/plan.sh
This will keep retrying to obtain the state lock for 5 minutes before failing.
Current behaviour is to fail immediately, and the only sensible action is to retry it manually.
5 minutes should be long enough that it's quicker than noticing and retrying manually, but not long enough
that builds are stuck if the state lock is stale.
It's not exposed as an option, but it should address the issue seen #113
I've adapted the terraform orb for GitHub actions, and this is one of the changes I made on the way. 
Check it out: https://github.com/dflook/terraform-github-actions
=> Set a lock-timeout

terraform/CHANGELOG.md, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12
Helm 2.16.1 install package has disappeared from its published location.
Newer versions are published somewhere else, so helm has been upgraded to 2.16.9 so we can use the new location.
=> Fix helm package url

versioned-lambda/orb.yml
Small fix to the node12.x lambda version we are using to prevent build-stopping errors in CI.
=> Update version with working image

versioned-lambda/README.md, versioned-lambda/orb.yml
NPM Auth:
* Adds optional step to `node-test-and-package` to authenticate with npm if a token is provided in the environment variables.
* Defaults to `true` because we assume that most projects that would use this orb would be using ovotech repositories.
Shipit:
* Adds `notify-shipit` optional step to `create-lambda-version`
* defaults to `false`
Readme updated to reflect new options.
=> Add npm authentication & shipit to versioned-lambda

clojure/orb.yml, clojure/orb_version.txt, oot-eks/orb.yml, oot-eks/orb_version.txt
Note also that the versions have been bumped to `1.0.1` - this is because the initial publish seemed to force a version of `1.0.0` over the `0.1.0` specified in the `orb_version.txt`.
=> Add descriptions to OOT orbs.

terraform/CHANGELOG.md, terraform/README.md, terraform/executor/Dockerfile-0.12-slim, terraform/orb_version.txt
I understand the slim executor should have the latest version.
Aiven worked out the ACL username validation issues and we tested
that locally just running tf plan for the kafka-uat config in
aiven as code.
Aiven have also changed the structure of the filenames of their
release assets. Made some changes to executor to accommodate
After this I'll look at changing the executor for the uat jobs in aiven as
code over to using the slim executor. Not going ahead and updating 
the executor all the aac jobs use is just out of caution around 
the ACL username validation issue in particular and the fact that we’ve
not updated the version we’re using since February so there is some 
risk from the unexpected. There is a major version bump too.
=> upgrade aiven provider version for slim

clojure/orb.yml, clojure/orb_version.txt
...as there seems to be an occasional race condition between scanning and running the test job.
=> Clojure orb: Ensure that all maven dependencies are pulled down before running snyk scan

rac-gcp-deploy/executor/Dockerfile, terraform/CHANGELOG.md, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12, terraform/executor/Dockerfile-0.12-slim, terraform/executor/Dockerfile-0.13, terraform/orb_version.txt
This adds the new `terraform-provider-aiven-kafka-users` (which has cred rotation cababilities) to the terraform orb.
=> Add tf-provider aiven-kafka-users

terraform/CHANGELOG.md, terraform/github.py, terraform/orb_version.txt
Reverts the changes made in #158, I saw a failed job when using the new orb version with comments on a PR from an old version. I've still not tracked any specific errors down, but safer to revert for now I think..
=> Revert HCL highlighting

terraform/CHANGELOG.md, terraform/apply.sh, terraform/comment_util.py, terraform/github.py, terraform/orb_version.txt, terraform/plan.sh, terraform/test_comment_util.py
- created `terraform/comment_util.py` with functions for regex matching and creation of the comment that's put onto PRs, and updated `terraform/github.py` to use new functions
- created `terraform/test_comment_util.py` with some tests in
- updated the `terraform/plan.sh` and `terraform/apply.sh` to copy new util python file to `/tmp`
I tested the devorb, and both plan and apply were successful (with HCL highlighting).
I haven't been able to test the case of a plan being done on old version, and apply being done on new version, but I think my unit tests cover that.
Credit to @gordonkeogh for the initial work on this; this PR is just to fix the changes on #158
=> Add hcl formatting

oot-eks/orb.yml
Sets `{{AWS_REGION}}` in kuberetes yaml in oot builds.
This is required for pods which need to sign requests with IAM credentials (e.g. oot-work-items-v2 which needs to sign its requests to Elasticsearch).
=> Set AWS_REGION in kubernetes yaml for oot services

oot-eks/orb_version.txt
This should have been updated in b18bda91c539adcabf018ffe80b37ea441c34221
(Set AWS_REGION in kubernetes yaml for oot services)
=> Bump oot-eks orb version

rac-gcp-deploy/orb.yml
Ancient version bundled in executor image limits JVM metaspace unnecessary
=> RNC-781 rac-gcp-deploy: bump sbt launcher version to 1.4.1

.github/CODEOWNERS, README.md, oot-deploy/README.md, oot-deploy/orb.yml, oot-deploy/orb_version.txt
This orb is designed for OOT to use in deploying services via gitops using ArgoCD. However, it has been documented in such a way that it should be reusable by other folks (within the limits of the interpolation and expected gitops file structure anyway).
=> Added new oot-deploy orb.

oot-deploy/orb.yml
Fixes this error: https://app.circleci.com/pipelines/github/ovotech/circleci-orbs/684/workflows/32813727-00a0-4bf2-bd26-f39f7a4a8a3c/jobs/4889
=> Correct gitops-ssh-key-fingerprint parameter to oot-deploy orb.

oot-deploy/README.md, oot-deploy/orb.yml, oot-deploy/orb_version.txt, oot-eks/README.md, oot-eks/orb.yml, oot-eks/orb_version.txt
The main purpose of this PR is to split the functionality building OOT docker images (`oot-eks`) apart into an orb separate from the functionality to update our gitops repo (`oot-deploy`). The key advantage of this is it potentially allows other teams to use the `oot-deploy` orb without having to also be on AWS EKS.
`oot-eks` becomes something of a misnomer (`oot-ecr` would be more accurate now) but given that this is a team specific orb, the confusion is going to be minimal.
Because of the major changes, both orbs are bumped a major version number.
=> Split OOT image building and gitops deployment across two separate orbs for more flexible reuse.

oot-deploy/README.md, oot-deploy/orb.yml, oot-deploy/orb_version.txt
Rather than relying on users adding new services to Argo by hand in the Argo console, get the `oot-deploy` orb to do the hard work of generating a [argoproj.io/v1alpha1](https://argoproj.github.io/argo-cd/operator-manual/application.yaml) resource representing the service being deployed.
=> Create argo application resource as part of oot-deploy gitops process.

terraform/CHANGELOG.md, terraform/apply.sh, terraform/check.sh, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12, terraform/executor/Dockerfile-0.12-slim, terraform/executor/Dockerfile-0.13, terraform/executor/compact_plan.py, terraform/executor/test_compact_plan.py, terraform/orb_version.txt, terraform/plan.sh, terraform/setup.sh
With Terraform 0.14, the plan output no longer has the `----` separator line between the boring bit and the interesting bit of the plan.
If we want to work with versions past 0.14, we need to be a bit smarter.
=> Fix empty plan in PR comments with terraform 0.14

terraform/CHANGELOG.md, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12, terraform/executor/Dockerfile-0.12-slim, terraform/executor/Dockerfile-0.13, terraform/orb_version.txt
Build for the tf orb has been failing with 
`Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden`
Guided by https://helm.sh/blog/new-location-stable-incubator-charts/ and https://stackoverflow.com/questions/61954440/how-to-resolve-https-kubernetes-charts-storage-googleapis-com-is-not-a-valid , adds the updated stable repo url.
=> Specify updated stable repo for helm 2

clair-scanner/executor/Dockerfile
This PR pins the base image in the clair scanner Dockerfile to `golang:1.15` instead of `golang:latest`. 1.16 was released a couple of days ago which seems to be breaking the build.
=> Pin Clair Scanner to golang:1.15

terraform/apply.sh
Adds the `$chdir` variable to tf apply
If the user has chdir functionality enabled, the `plan.out` from the preceding tf plan would have been created in the `$chdir` directory (so currently all tf apply operations with chdir in the orb will be failing after the apply is done).
Users without chdir func enabled should be uneffected.
Tested the devorb on both paths (chdir enabled/disabled).
=> Add chdir to plan out path

.circleci/config.yml, gcp-rotate-keys/README.md, gcp-rotate-keys/orb.yml, gcp-rotate-keys/orb_version.txt, gcp-rotate-keys/scripts/delete-key.sh, gcp-rotate-keys/scripts/deploy-file-to-ssm.sh, gcp-rotate-keys/scripts/generate-key.sh, gcp-rotate-keys/scripts/get-existing-key.sh, gcp-rotate-keys/scripts/redeploy-ecs.sh, gcp-rotate-keys/scripts/redeploy-fargate.sh, gcp-rotate-keys/scripts/validate-service-account.sh
This PR adds a new orb to the repository called `gcp-rotate-keys`. It is designed to help teams rotate their GCP service account credentials.
In my team, our use case involves adding the new key to SSM and redeploying a Fargate service before deleting the old key, in order to prevent any downtime. We were unable to fulfil this requirement with existing tools (e.g. the cloud key rotator) so I have written an orb that is hopefully re-usable by others as well.
The orb has two commands - `rotate-gcp-key` which takes a series of steps to perform actions after creating the new key but before deleting the old one, and `rotate-gcp-key-in-aws-ssm` which will upload the key in AWS SSM Parameter Store before running the series of steps.
It also includes a single job - …
=> Add GCP Rotate Keys orb

gcp-rotate-keys/orb.yml, gcp-rotate-keys/orb_version.txt, gcp-rotate-keys/scripts/maybe-decode.sh
This PR updates the `rotate-key-redeploy-ecs-service` job in the `gcp-rotate-keys` orb to be able to decode the GCP service account key if it has been base64 encoded (for example, if it has been rotated by cloud key rotator).
=> [GCP Rotate Keys] Decode base64 encoded keys if necessary

terraform/comment_util.py, terraform/orb_version.txt, terraform/test_comment_util.py
Good afternoon
Terraform plan comments can get pretty long sometimes, so I thought this would be useful.
The plans would be open by default and can be collapsed.
They look like this:
Terraform plan for __non-prod-cluster__
<details open>
<summary>Plan</summary>
```hcl
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Warning: Version constraints inside provider configuration blocks are deprecated
on cluster/main.tf line 29, in provider "aws":
29:   version = ">= 2.28.1"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a …
```
=> Make Terraform Plan Comments Collapsible

sbt-deploy/README.md, sbt-deploy/orb.yml, sbt-deploy/orb_version.txt
- SSH fingerprint is now optional
- Now allows a custom SSH key host mapped to hostname to be specified (for when additional SSH keys have identical hosts).
=> Allow custom SSH key host + make fingerprint optional

gcp-rotate-keys/orb_version.txt, gcp-rotate-keys/scripts/redeploy-ecs.sh
This PR improves the timezone handling with `jq` when comparing dates of events.
=> gcp-rotate-keys: Better timezone handling

rac-gcp-deploy/orb.yml
This plugin is now deprecated as it's been integrated directly into Sbt.
This plugin contains dependencies that are still hosted in Bintray. Given that the plugin is deprecated and Bintray is going to be terminated on 1st May, it's probable that the plugin is not going to be updated. If this is the case, it will cause our builds to fail.
Given that most of our services are using sbt > 1.4.x, I prefer to remove the injection of the plugin and update the services that might fail due to lack of it. 
Deprecation notice: https://github.com/sbt/sbt-dependency-graph
=> Remove sbt-dependency-graph

rac-gcp-deploy/orb.yml
This PR makes it possible to deploy UAT first before deploying PRD. 
It's done by splitting a single release step into 2 separate steps:
1. `build_and_release_version` - Release a new version, push it to git, build Docker image locally and save it to the file
2. `push_docker_image` - Push Docker image built in 1. to the registry
Example how application can used those steps in order to deploy UAT first, and then PRD:
1. `orb/build_and_release_version`
2. `orb/push_docker_image` configured with UAT
3. Wait for human approval
4. `orb/push_docker_image` configured with PRD
Examples can be seen [here](https://github.com/ovotech/rac-trigger/blob/master/.circleci/config.yml) and [here](https://app.circleci.com/pipelines/github/ovotech/rac-trigger/358/workflows/61f56ee8-2e4a-4f88-8282-2a21be2b0af6 …
=> [RNC-1989] Add a job to release a single image

jaws-journey-deploy/scripts/save_test_results.sh, jaws-journey-deploy/scripts/update_helm.sh
- Retry committing manifests in case head of the branch has moved
- Ensure `./reports/jacoco/` directory is empty
- Include environment in manifest commit
=> Fix: jaws gitops deploy

terraform-v2/CHANGELOG.md, terraform-v2/orb_version.txt, terraform-v2/setup.sh, terraform-v2/v1-to-v2.md
The new terraform-v2 orb only support terraform >= 0.14. Currently it fails with an unclear message if you try to use an older version of terraform. This hopefully makes it clearer. It'll need adjusting when terraform v1 comes out but I imagine a number of things will need changing when that happens.
=> Add version check to new terraform-v2 orb

terraform-v2/orb.yml, terraform/executor/Dockerfile
Fixes this error
```
error downloading 'https://github.com/ovotech/terraform-module-fargate-app.git?ref=3.1.8': git must be available and on the PATH
```
when using git sourced terraform modules.
Not bumping the orb version as the terraform-v2 orb pulls the latest tag, so all versions will be updated by this.
=> Add git into terraform v2 docker image

terraform/CHANGELOG.md, terraform/orb_version.txt, terraform/setup.sh
The terraform fails with an unhelpful message currently if you try to use it with terraform 0.15+. This makes the error message more explicit and helpful.
=> Prompt terraform 0.15 users to use the v2 orb

argocd/orb_version.txt
CircleCI seems to have published this as 1.0.0, not 0.1.0.
=> Bump argocd version

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
Resolves this issue [https://app.circleci.com/pipelines/github/ovotech/jaws-journey-reconcile-device-store/338/workflows/44c9ff62-a97a-426d-abb5-9d5db6d2c298/jobs/3341](https://app.circleci.com/pipelines/github/ovotech/jaws-journey-reconcile-device-store/338/workflows/44c9ff62-a97a-426d-abb5-9d5db6d2c298/jobs/3341)
Some more context [https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/)
=> Update aws-ecr orb to fix python2 deprecation

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
ArgoCD reports as being 'in-sync' while still (for example) rolling out
new pods in a statefulset. The 1.0.1 fixes this by waiting until the Argo
Application is no longer 'Progressing'.
=> Fixes ArgoCD up not waiting until application has finished progressing

comms-commands/orb.yml
This change allows us to call the plan/apply default jobs from a project which has multiple modules with the module_name as a matrix parameter
=> Comms orb - call terraform plan/apply default jobs with module name

comms-commands/orb.yml, comms-commands/restart_ecs_service.sh
Allows for waiting the completion of an ECS deployment without restarting the
service.
=> Add a wait_for_ecs_deployment command

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
Noticed the npm build job was always fetching from the cache even when the package-lock.json file had changed. Looks like cache-key template in circleci needs curly brackets. See [here](https://circleci.com/docs/2.0/caching/?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gb-DSA-Eng-emea&utm_content=&utm_term=dynamicSearch-&gclid=Cj0KCQjwsZKJBhC0ARIsAJ96n3WWeNgkJ3kMWJm5_ecyTN5gMtl26qbXO4JimB0YSHo1d7pScuAotHIaAoYIEALw_wcB#using-keys-and-templates).
=> fix: circle-ci cache-key template needs 2 curly brackets

terraform-v2/cmp.py, terraform-v2/orb_version.txt
Terraform 0.15.4 starts to report upon the drift changes that have been
detected rather than silently updating its state. One of the attributes
that is now reported includes the latest_restorable_time attribute for RDS
databases.
These drift changes are reported as part of the Terraform plan. Thus,
these changes are also included in the comparison when checking for
approval.
For AWS computed attributes this causes a problem. PITR and database
backups can constantly modify the latest_restorable_time attribute,
meaning that almost every single plan returns a more recent time.
Therefore it's almost impossible for this attribute to ever match what
was in the approved plan, as even if only a few minutes have passed
since the plan was approved the attribute has likely updated again.
We can …
=> Ignore terraform changes to latest_restorable_time

terraform-v2/publish.sh, terraform/publish.sh
Currently if a terraform module is published without bumping the module
version it will overwrite the existing version. That could cause issues
for users of that module if it includes breaking changes.
This checks if a version already exists before publishing.
=> Update publish module script to prevent overwriting previous versions

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
As of Dec 31, 2021, legacy images will no longer be supported on CircleCI. Updating OpenJDK, python and node images.
For more information see here: https://circleci.com/docs/2.0/next-gen-migration-guide/
=> ci: update openjdk from legacy CircleCI image to latest version

terraform-v2/CHANGELOG.md, terraform-v2/comment_util.py, terraform-v2/orb_version.txt, terraform/CHANGELOG.md, terraform/comment_util.py, terraform/orb_version.txt
We have identified that 1.11.2/2.4.3 introduced a bug where the Orb is no longer able to pull the plan from a comment, which is used both to determine whether to create or update a comment as well as to compare with the plan from the PR before applying.
While we investigate further, this PR just reverts this functionality so that teams can continue to use the Orb without pinning the version.
=> revert collapsible terraform plans

aws-rotate-keys/CHANGELOG.md, aws-rotate-keys/orb.yml, aws-rotate-keys/orb_version.txt
This fixes the issue with the version `'2'` that was specified previously which made the job fail if the default executor was used since the install command requires a full version to be specified. I've made it use the latest v2 version by omitting the version parameter.
=> [aws-rotate-keys] Default to installing the latest AWS CLI v2 if the binary is not present on the PATH

.circleci/continue_config.yml, terraform-v2/CHANGELOG.md, terraform-v2/comment_util.py, terraform-v2/orb_version.txt, terraform-v2/test_comment_util.py, terraform/CHANGELOG.md, terraform/comment_util.py, terraform/orb_version.txt, terraform/test_comment_util.py
This PR fixes the Terraform and Terraform-v2 orbs PR comment matching functionality. The comment matching method wasn't updated when the format of the comment was updated, so the orb became unable to correctly detect plans / update comments on PRs, etc.
It also adds a stage to the CI pipelines for these two orbs to run the existing python tests, so that this problem won't crop up again in the future (hopefully)
=> Re-enable terraform orb collapsible plans

oot-eks/orb.yml, oot-eks/orb_version.txt
Also, bump minor versions of other orbs referenced in oot-eks orb.
=> Allow extra arguments to be passed to docker build from oot-eks orb.

rac-gcp-deploy/orb.yml
This adds a new job to the R&C orb, to push an image to the centralised image registry where it can be pulled in by KMI. The AWS_ECR_ACCOUNT_URL and AWS_REGION environment variables have already been added to the main R&C context but the AWS image pushing credentials will need to be added per service, as they are different for each namespace.
I have not added this new job to the README as the image pushing jobs don't seem to be in there and I wanted to double check if this is a deliberate choice, given the orb is public?
I'm also not sure how to increase the version for this orb, as I can't see an orb_version.txt file?
=> Add KMI image push job to RaC orb

.circleci/config.yml, .circleci/continue_config.yml, helm-ci/README.md, helm-ci/executor/Dockerfile, helm-ci/orb.yml, helm-ci/orb_version.txt
Teams moving to KMI are being encouraged to use helm in their gitops repositories. I'm finding there's a lot of duplication in the CI for those gitops repositories and there doesn't seem to be a good open source circleCI orb for Helm CI, so creating one.
This is quite focused on the KMI use-case - e.g. it assumes you will have values files associated with the chart and no values being passed in directly in the helm templating step. I think this is acceptable for a first version of the orb and we can add parameterisation for other use cases in future.
https://app.circleci.com/pipelines/github/ovotech/energy-contracts-kmi-gitops/104/workflows/f0ca0afe-3d3e-4c54-9e6b-2faca77a8e7b/jobs/187 is an example of the orb running.
=> Add Helm CI orb

rac-gcp-deploy/README.md, rac-gcp-deploy/orb.yml
This commits the new version tag to the rac-kmi-gitops repo, kicking off a deployment in KMI.
=> RNC-2456 Add KMI deployment step to RAC orb

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
Legacy circleci python images are being deprecated. so moving to `cimg` images. Having to install the `requests` module
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
=> update to cimg image

asp-deploy/orb.yml
Add a sed to replace the tag on the kustomize patch files, this way updating the datadog version on the deployment step.
=> Add datadog tags on deployments

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
The download link got changed a while ago
https://github.com/snyk/snyk-orb/commit/46f6fa5ca3a7e782d2b22ff19bc4920827b5f530
So bumping to snyk/snyk@1.1.2
=> fix: update snyk orb

rac-gcp-deploy/orb.yml
Older images will soon be deprecated by CircleCi
https://circleci.com/blog/ubuntu-14-16-image-deprecation/
=> Update image for machine executor

oot-eks/orb.yml
Bumping oot eks docker image from 16 to 20.04
https://circleci.com/blog/ubuntu-14-16-image-deprecation/
=> Bump docker ubuntu image to 20.04

jaws-journey-deploy/orb_version.txt, jaws-journey-deploy/scripts/get_coverage.py
In a PR if you click on the code coverage links for a particular project it will show `Artifact not found`
=> fix: updating code coverage link

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
Added command which supports build and pushing of images to KMI ECR. Also added undefined environment enum option for scenarios where builds are environment agnostic.
=> Add publish to KMI ECR command to JAWS deploy orb

ipa-deploy/README.md, ipa-deploy/orb.yml, ipa-deploy/orb_version.txt
Wrapping parameter in double quotes was causing param string double quotes to disappear. 
Using single quotes on script instead.
=> Fix IPA deploy script quotes

README.md, helm-ci/CHANGELOG.md, helm-ci/README.md, helm-ci/orb.yml, helm-ci/orb_version.txt
This uses a small executor by default. It also updates the documentation and corrects the version to be 1.x.x as it looks like CircleCI [overwrites the version with 1.0.0](https://circleci.com/developer/orbs/orb/ovotech/helm-ci) if it's 0.x.x when published.
=> Use smaller executor for helm-ci orb

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
With the security dashboard flagging medium vulnerabilities, we need the ability to flag them during builds
=> Jaws snyk scan threshold parameter

jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt, jaws-journey-deploy/scripts/automated_test_run.sh
In MARS we have the ability to run 2 parallel environments and during automated testing we need to identify which environment is being tested (in order to determine which database to use).
Added a new environment variable of 'DEPLOYMENT' to the run-automation-test job to enable this, which defaults to an empty string.
=> feat: jaws automated test env variables

oot-eks/orb.yml, oot-eks/orb_version.txt
KMI has made their ECR tags immutable. `oot-eks` tags images with both the build hash and `latest`, causing KMI ECR to complain it’s trying to update an immutable tag (`latest`).
This PR provides a parameter to specify tags and get around this problem
=> Allow tags to be specified when building/pushing with oot-eks

terraform/executor/Dockerfile
There is a current issue with the original tfswitch as hashicorp changed
their website and so the bit of tfswitch which scrapes that info is
failing. This is a temporary fix until the PR is merged on tfswitch.
github issue: https://github.com/warrensbox/terraform-switcher/pull/225
differences between versions: https://github.com/warrensbox/terraform-switcher/compare/master...Jukie:fix-release-downloads
---
Alrighty - so this may not be needed by tomorrow if the tfswitch people wake up and merge their PR - at which point we just need to update to the latest version. But opening this PR so that we can merge the change and people can run their terraform still if that is going to take a while
=> Update to using the Jukie repo for tfswitch in terraform docker container

terraform-v2/CHANGELOG.md, terraform-v2/orb_version.txt, terraform/CHANGELOG.md, terraform/executor/Dockerfile, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12, terraform/executor/Dockerfile-0.12-slim, terraform/executor/Dockerfile-0.13, terraform/orb_version.txt
Increment versions for orbs as its now a new version of tfswitch
=> Revert back to original repo for tfswitch and get latest version (0.13.1221)

aws-configure-credentials-oidc/orb.yml, aws-configure-credentials-oidc/orb_version.txt
* Updated to use the latest `circleci/aws-cli@3.0.0` orb. https://circleci.com/developer/orbs/orb/circleci/aws-cli
* Give the assume role/configure step a friendly name, instead of showing entire STS line
=> Update aws-cli orb and use friendly name for assume step

.circleci/config.yml, .circleci/continue_config.yml, .github/CODEOWNERS, kap-kmi-deploy/README.md, kap-kmi-deploy/orb.yml, kap-kmi-deploy/orb_version.txt
Creates a new `kap-kmi-deploy` orb for use by the KAP squad in deploying services to KMI.
See the [README](https://github.com/ovotech/circleci-orbs/tree/kap-kmi-deploy/kap-kmi-deploy) for details.
=> Add new kap-kmi-deploy orb.

clojure/orb.yml, clojure/orb_version.txt
This ensures that any violations that are picked up by the scanning step are available to suppress in the dashboard - currently the `monitor-on-build` option only kicks in if the scan itself passes.
=> Force a snyk monitor whenever building Clojure projects

rac-gcp-deploy/orb.yml
Add remote tracking branch before sbt release, to allow for releasing non main/master branches
=> [RNC-2860]: Add remote tracking branch before sbt release

jaws-journey-deploy/changelog.md, jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt, jaws-journey-deploy/scripts/github_docker_login.sh
upversioning to circleci/aws-ecr@8.1.3 and allowing usage of oidc instead of aws keys/secrets if specified
This version uses oidc for the relevant jobs if the oidc parameter is set to true. Otherwise it will look for AWS keys as before by default
The newer aws-ecr version uses a newer docker version + buildx which doesn't seem to work with the deprecated github container repo url (docker.pkg.github.com). It fails to pull images with 401's despite a login using the same url. 
So i've changed the login to use the new url (ghcr.io). This is the breaking part of the change and requires any github container repo urls in dockerfiles to be amended to ghcr.io
CIRCLE_IAM_ROLE_ARN (optional)
AWS_ACCOUNT_ID (already in jaws contexts)
ACCOUNT_URL
=> BREAKING CHANGE: allowing usage of oidc instead of aws keys if specified

.circleci/config.yml, .circleci/continue_config.yml, .github/CODEOWNERS, build-utilities/CHANGELOG.md, build-utilities/README.md, build-utilities/orb.yml, build-utilities/orb_version.txt
New `orb` called `build-utilities` which contains a bunch of repetitive commands in our `config.yml`
This should open access to a getting - from another internal repo - a set of internal `bash` scripts used to create multi-arch images and store them in a manifest to a private docker registry.
Tested `orb` in a project - https://app.circleci.com/pipelines/github/ovotech/homeservices-customer-signup?branch=CGI-20520-add-orb
=> Cgi 20520 multi arch image build utility

rac-gcp-deploy/orb.yml, rac-gcp-deploy/orb_version.txt
* [Adds target-file](https://github.com/ovotech/circleci-orbs/commit/5d318fc48bca91326c1e8cdf048202f56baa62bd) Since c&e projects don't have a standard Dockerfile in root, snyk won't be able to auto-detect it and provide base image remediation advice.
* [Exposes monitor-on-build parameter](https://github.com/ovotech/circleci-orbs/commit/f9d8fabb5b6b826fe61f6cc13087c921e881174c)
=> Updates rac-gcp-deploy

rac-kmi-deploy/orb.yml, rac-kmi-deploy/orb_version.txt
⚠️ Depends on #506
At the point where we add snyk monitoring of project dependencies, we now also monitor the container
~After https://github.com/ovotech/circleci-orbs/pull/506 is merged, core dependency can be updated to ovotech/rac-gcp-deploy@1.1.0~ ✅
=> Updates rac-kmi-deploy

rac-gcp-deploy/orb.yml, rac-gcp-deploy/orb_version.txt
v 1.3.0+  is returning a weird
```
Downloading Snyk CLI version 1.1076.0
snyk-linux: OK
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility.
[sudo] password for circleci:
sudo: no password was provided
sudo: a password is required
Exited with code exit status 1
```
=> Downgrade snyk orb

rac-kmi-deploy/orb.yml, rac-kmi-deploy/orb_version.txt
Currently, the EU1 UAT environment works as a development environment, very different to the OEA-owned AP1 UAT (Sandbox). Because of this, on a merge to main we will want to release automatically to EU1 UAT but not AP1 UAT, hence the introduction of a kmi-region parameter that allows us to release on specific regions.
=> Adds kmi-region param to deploy job

kap-kmi-deploy/orb.yml, kap-kmi-deploy/orb_version.txt
Attempting to bump aws-ecr orb version for kap-kmi-deploy orb to overcome deployment bug
https://github.com/CircleCI-Public/aws-ecr-orb/issues/200
=> OOT Bumping aws ecr orb version for kap-kmi-deploy orb

oot-eks-oidc/README.md, oot-eks-oidc/orb.yml, oot-eks-oidc/orb_version.txt
Over in the Kaluza Agent Platform/Experience, Ops Tooling are looking to replace the IAM user with an OIDC provider in our oot-eks deploy orb. This is according to guidance from the sec eng team to remove aws iam users.
This PR sets up a temporary orb that we can use for testing this process.
=> OOT-2476 OIDC for oot-eks orb

oot-eks-oidc/orb.yml, oot-eks-oidc/orb_version.txt
The oot-ecr-oidc orb is still not deploying. This PR attempts a version bump to see if that helps.
=> OOT-2476 Try a version bump to get orb to deploy

kap-kmi-deploy/README.md, kap-kmi-deploy/orb.yml, kap-kmi-deploy/orb_version.txt
Adds ability to specify which region (e.g. "eu1", "ap1") to update gitops on.
In Workflow we want to be able to release to oea-test and ovo-uat at the same time, have a manual approval step, and then progress the build to oea-sandbox and ovo-prod. We'd need to be able to specify the region to deploy to ovo-uat without affecting oea-sandbox (which is uat in git-ops).
=> kap-kmi-deploy: add region param to job

jaws-journey-deploy/changelog.md, jaws-journey-deploy/orb.yml, jaws-journey-deploy/orb_version.txt
Recent versions of the orb retry the notoriously flaky CLI download step
=> JAWS Orb: bump Snyk orb version

terraform-v2/apply.sh, terraform-v2/orb.yml, terraform-v2/orb_version.txt, terraform-v2/plan.sh
This PR addresses various issues occurring when:
-  terraform plan is generated, 
- posted to Git 
- and comapred before applying
Causes of 'Plan has changed' issue in various scenarios:
1. Plan has `Releasing state lock. This may take a few moments...` in either git comment or in the plan generated before apply for comparing with git comment
2. Warning in the plan: There can be multiple terraform resources of same type having same warning, terraform reports warning for the first resource it tried to refresh and this first resource could be any any one of the same resources (not same one due to parallel processing)
hence causes plan has changed issue.
- Generating the `plan.txt` file from the terraform's plan.out file instead of the console output of `terraform plan` command. This ensures …
=> generate clean terraform plan with only changes

.circleci/config.yml, .circleci/continue_config.yml, .github/CODEOWNERS, release-notes/CHANGELOG.md, release-notes/README.md, release-notes/orb.yml, release-notes/orb_version.txt
This orb provides ability to publish release data (version and release notes) to release notes system on every successful semantic release occurrence. It works in conjunction with ArgoCD Notifications
=> feat: add release note orb

argocd/README.md, argocd/orb_version.txt, argocd/scripts/wait_for_sync.py
With newer versions from argocd, without the explicit content type the json will be unreadable.
Similar work was done for the GitHub actions in [this PR](https://github.com/ovotech/kaluza-github-actions/pull/56/files).
=> feat: add explicit content-type

terraform-v2/CHANGELOG.md, terraform-v2/orb_version.txt, terraform/CHANGELOG.md, terraform/executor/Dockerfile, terraform/executor/Dockerfile-0.11, terraform/executor/Dockerfile-0.12, terraform/executor/Dockerfile-0.12-slim, terraform/executor/Dockerfile-0.13, terraform/orb_version.txt
Including the new end-of-life provider version for the legacy v1 user provisioner. See [kafka-users#19](https://github.com/ovotech/kafka-users/pull/19) for more details
=> include tf provider v1.9.9

terraform-v2/CHANGELOG.md, terraform-v2/github.py, terraform-v2/orb_version.txt
This causes the check that a PR plan hasn't changed when applying to constantly fail.
Mistakenly added in 97dce86 and confirmed with author.
=> Dropped debug output that's appearing in Terraform plan text

terraform-v2/CHANGELOG.md, terraform-v2/orb_version.txt, terraform-v2/setup.sh, terraform-v2/test.py
This PR disables xtrace when testing for presence of and handling the environment variable `$TF_REGISTRY_TOKEN`, which is a sensitive value.
=> Prevent disclosure of registry credentials in logs in the Terraform V2 orb

.circleci/continue_config.yml
linked to: https://kaluza.atlassian.net/jira/software/c/projects/QE2/boards/497?selectedIssue=QE2-1003 
Updating the version used as given version is affected by https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176
=> update docker version used
