ovotech/circleci-orbs

- terraform/README.md
- terraform/apply.sh
- terraform/get_plan.py
- terraform/orb.yml
- terraform/plan.sh
- terraform/put_plan.py
The environment parameter can be used to label a terraform plan/apply for a friendlier PR message.
This must be used if you have multiple plans of the same directory + workspace in the same repo.
> Add label parameter for plan & apply

- terraform/README.md
- terraform/apply.sh
- terraform/check.sh
- terraform/destroy.sh
- terraform/init.sh
- terraform/orb.yml
- terraform/plan.sh
Adds new-workspace, destroy-workspace, and support for TF_WORKSPACE
> Add workspace commands

- terraform/apply.sh
- terraform/get_plan.py
- terraform/orb.yml
- terraform/plan.sh
- terraform/put_plan.py
Apply will always fetch the correct plan. Even if there is no label.
> :memo: Save terraform init and plan arguments with the plan.

- terraform/orb.yml
Addressing https://github.com/ovotech/circleci-orbs/issues/11. @danielflookovo I can EOF it if you think that's nicer.
> Check workspace before create

- clair-scanner/orb.yml
- clair-scanner/scan.sh
Save the clair-scanner report as a circleci artifact
> :memo: Save the clair-scanner report as a circleci artifact

- terraform/apply.sh
- terraform/destroy.sh
- terraform/orb.yml
remove execs that no longer make sense
> Fix auto-approve

- terraform/executor/Dockerfile-0.11
- terraform/executor/Dockerfile-0.12
This provides a means to parse output from the AWS CLI.
> Add jq to Terraform Dockerfiles

- rac-gcp-deploy/executor/Dockerfile
- rac-gcp-deploy/orb.yml
use a custom docker image with all the necessary software
remove installation of gcp tooling
change default registry to `eu.gcr.io`
> Use custom docker image for rac-gcp-deploy

- rac-gcp-deploy/orb.yml
`image.tag` value wasn't being set properly
> set the docker image tag correctly

- terraform/apply.sh
> Update status when beginning plan for apply

- aws-rotate-keys/orb.yml
aws-rotate-keys orb: waiting until new token is usable
> aws-rotate-keys: wait until new token usable

- terraform/CHANGELOG.md
- terraform/executor/Dockerfile-0.11
- terraform/executor/Dockerfile-0.12
- terraform/orb_version.txt
Continuation of https://github.com/ovotech/circleci-orbs/pull/97,  but changed branch name to fix build
> Fix aiven provider download

- terraform/CHANGELOG.md
- terraform/executor/Dockerfile-0.11
- terraform/executor/Dockerfile-0.12
- terraform/orb_version.txt
> Updated executors to include wget

- terraform/README.md
Small documentation improvements.
Minor error case improved handling.
> Update TF Orb Documentation

- .circleci/config.yml
orb versions can't have slashes
> Cope with slashes in branch names

- .circleci/config.yml
- CODEOWNERS
- README.md
- set-current-environment/README.md
- set-current-environment/orb.yml
Set environmental variable (default ENVIRONMENT) from current branch. Defaults to prod for tags, nonprod for main branch and sandbox otherwise. Default name for main branch is master. Also tidied up config.yaml file and removed requirement for publish-docker-image parameter
> Set current environment

- versioned-lambda/orb.yml
- versioned-lambda/orb_version.txt
* Lowered snyk severity threshold to low
* Bumped version to 1.0.1
> Lower snyk severity threshold

- terraform/executor/Dockerfile-0.13
- terraform/orb.yml
Also removed the old aiven tf providers
> Add TF 0.13 executor

- terraform/executor/Dockerfile-0.11
Author moved the upstream to -old
> Terraform-0.11: Fix broken ACME links

- rac-gcp-deploy/executor/Dockerfile
- rac-gcp-deploy/orb.yml
> rac: Show evicted versions when compiling

- oot-eks/orb.yml
- oot-eks/orb_version.txt
Workaround for this: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/344
> Workaround for issue with kubernetes-sigs version

- oot-eks/orb.yml
- oot-eks/orb_version.txt
Incorporate the new `ovotech/ssh-proxy` orb into the OOT EKS deployment flow.
> Incorporate k8s-proxy into oot-eks orb.

- jaws-journey-deploy/README.md
- jaws-journey-deploy/build_lib.sh
- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/save_test_results.sh
Add ability to build libs separately to resolve issue with same files being created in separate workspaces
> Change save test results

- terraform/CHANGELOG.md
- terraform/README.md
- terraform/executor/Dockerfile-0.13
- terraform/orb_version.txt
as per https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers and https://ovoenergy.slack.com/archives/CC3CFQY0M/p1603797335366300
> use new local filesystem layout for inhouse plugins

- jaws-journey-deploy/README.md
- jaws-journey-deploy/automated_test_run.sh
- jaws-journey-deploy/build_project.sh
- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
+ add gradle parameter for running e2e tests.
> Skip unit tests in jaws deploy orb

- oot-deploy/README.md
- oot-deploy/orb.yml
- oot-deploy/orb_version.txt
Creates a new `extra-interpolations` parameter for the `oot-deploy` orb that allows for extra interpolations beyond the core replacements supported by the orb.
See https://github.com/ovotech/circleci-orbs/pull/207/files#diff-220ba54aabaf59f21ee4492855236b043f323d664e22e17d23ffeb1d2800ebbaR77 for an example.
> Added extra-interpolation parameter to oot-deploy orb.

- clojure/orb.yml
- clojure/orb_version.txt
- oot-deploy/orb.yml
- oot-deploy/orb_version.txt
Also includes changes to the oot-deploy orb.
> Bump to latest leiningen for clojure orb.

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/scripts/build_project.sh
- jaws-journey-deploy/scripts/persist_topology_diagram.sh
Update build step so that you can toggle whether to run the describe/save topology step
> Save topology

- versioned-lambda/orb.yml
Add boolean parameter monitor-branch and update snyk/scan step
> Add flag to conditionally monitor in Snyk

- terraform/CHANGELOG.md
- terraform/comment_util.py
- terraform/orb_version.txt
- terraform/test_comment_util.py
Reverts ovotech/circleci-orbs#226 - apply fails as the comparison logic doesn't handle checking the PR is the same at apply time as PR plan posted
> Revert "Make Terraform Plan Comments Collapsible"

- sbt-deploy/README.md
- sbt-deploy/orb.yml
- sbt-deploy/orb_version.txt
The example I had followed for Kustomize CLI download and usage were outdated.
> Fix permission issues in Kustomize CLI usage

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/scripts/commit_manifest.sh
- jaws-journey-deploy/scripts/configure_helm.sh
- jaws-journey-deploy/scripts/update_helm.sh
The current orb is failing with upstream not being set.
> Journeys helm update

- .circleci/config.yml
- README.md
- pipeline-utils/README.md
- pipeline-utils/orb.yml
- pipeline-utils/orb_version.txt
- pipeline-utils/scripts/configure-environment.sh
- pipeline-utils/scripts/maybe-decode.sh
This PR adds a new orb, tentatively called pipeline utilities. It is designed simply as a collection of commands that make life a bit easier when creating pipelines.
Currently there are two commands which should be well described in the README. Inspired by a [recent conversation on Slack](https://ovoenergy.slack.com/archives/CBFJV68US/p1617269997048100)
> Add a new orb: Pipeline utilities

- rac-gcp-deploy/orb.yml
This pr introduces several improvements, mainly to make our life easier while publishing libraries:
- new job to release libraries
- possibility to pass options to sbt commands
- cache key is now a parameter
> rac-gcp-deploy improvements

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/scripts/github_docker_login.sh
- jaws-journey-deploy/scripts/persist_topology_diagram.sh
So that we can use a base docker image stored on github we need to add a step to log into github before ecr upload step
> Add arg to docker push

- .circleci/config.yml
- .github/CODEOWNERS
- asp-deploy/README.md
- asp-deploy/orb.yml
- asp-deploy/orb_version.txt
Hey!
I'm adding this orb to reuse across our services' CircleCI configuration. This is the first time I create an orb so probably there's tons of room for improvement.
Cheers!
> Add ASP Deploy Orb

- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/scripts/update_helm.sh
Values passed to a chart dependency need to be nested under the name of the chart
> Fix path of buildTag and releaseVersion

- jaws-journey-deploy/orb_version.txt
Last PR did not bump the version
> Bump version

- terraform-v2/README.md
I missed some version fixes in the README :O
> Fix version in readme

- argocd/README.md
- argocd/orb_version.txt
- argocd/scripts/wait_for_sync.py
Also adds `ARGOCD_ORB_DEBUG` environment to help with debugging issues.
> Wait for target application to become healthy

- .circleci/config.yml
- .github/CODEOWNERS
- comms-publish-service/orb.yml
As the title suggests, a new orb for the comms team to share CCI code across comms services
> Comms team orb for publishing a service

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
Jumped the gun a little on my last one - turns out there was another breaking change when this got fixed [https://github.com/CircleCI-Public/aws-ecr-orb/issues/64](https://github.com/CircleCI-Public/aws-ecr-orb/issues/64)
> Fix jaws journey deploy orb

- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/scripts/update_helm.sh
https://ovotech.atlassian.net/browse/JF-194
> feat: remove quotes from the tag when pushing

- README.md
- aws-rotate-keys/CHANGELOG.md
- aws-rotate-keys/orb.yml
- aws-rotate-keys/orb_version.txt
> Bump aws cli version.

- terraform-v2/README.md
Just a small update to make it clearer how the GCP environment variables
relate to each other!
> Add info on GCP variable relations

- oot-eks/orb_version.txt
Trying to update orb. Update version?
> Try bumping orb version

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
all uat environment to be passed in
> add uat env

- .circleci/config.yml
- .circleci/continue_config.yml
- .github/CODEOWNERS
- README.md
- ipa-deploy/README.md
- ipa-deploy/orb.yml
- ipa-deploy/orb_version.txt
Adding IPA's team orb for shared deployment alert templates.
> Add IPA team deployment orb

- rac-gcp-deploy/orb.yml
Bump snyk version as failing snyk_monitor step
> Bump snyk orb version for rac-gcp-deploy

- terraform/executor/Dockerfile-0.11
- terraform/executor/Dockerfile-0.12
- terraform/executor/Dockerfile-0.12-slim
- terraform/executor/Dockerfile-0.13
github issue: warrensbox/terraform-switcher#225
differences between versions: warrensbox/terraform-switcher@master...Jukie:fix-release-downloads
> Use Jukie repo for tfswitch temporarily for the terraform-v1 orbs

- .circleci/config.yml
- .circleci/continue_config.yml
- .github/CODEOWNERS
- README.md
- setup-scheduled-pipeline/README.md
- setup-scheduled-pipeline/orb.yml
- setup-scheduled-pipeline/orb_version.txt
PR created by automated teamCPPEbot / See original pull request [here](https://github.com/ovotech/team-cppe/pull/23)
> CPPE addition / modification of CircleCI orb setup-scheduled-pipeline

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
- jaws-journey-deploy/scripts/automated_test_run.sh
Adding another environment variable to automated tests to enable tests to run for parallel deployments
> feat: Adding another environment variable to automated tests

- sast/README.md
- sast/orb.yml
- sast/orb_version.txt
> CPPE addition / modification of CircleCI orb sast

- jaws-journey-deploy/orb.yml
Update TF Orb version to fix tfswitch issue - https://ovoenergy.slack.com/archives/C7D5V1JMS/p1655713296162659
> increase version of tf module

- sast-terraform/orb.yml
- sast-terraform/orb_version.txt
> CPPE addition / modification of CircleCI orb sast-terraform

- terraform-v2/CHANGELOG.md
- terraform-v2/orb.yml
- terraform-v2/orb_version.txt
- terraform-v2/set_plan_args.sh
- terraform/CHANGELOG.md
- terraform/README.md
- terraform/orb.yml
- terraform/orb_version.txt
- terraform/set_plan_args.sh
This PR introduces the `target` parameter for the plan step.
We want to target specific resources in a plan so that when using `reuse_plan` parameter in apply step we only use those specific resources.
> add target parameter to plan

- terraform-v2/CHANGELOG.md
- terraform-v2/orb_version.txt
- terraform-v2/publish.sh
- terraform/CHANGELOG.md
- terraform/orb_version.txt
- terraform/publish.sh
> Fix authorization bearer for existing terraform version

- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
> fix: avro save cache

- rac-gcp-deploy/orb.yml
- rac-gcp-deploy/orb_version.txt
Depends on #506 (version-wise)
> Stores test results

- rac-kmi-deploy/orb.yml
- rac-kmi-deploy/orb_version.txt
Was returning `if [ "$all" = "all" ]; then...`
> Fixes kmi-region check

- rac-kmi-deploy/orb.yml
- rac-kmi-deploy/orb_version.txt
> Fixes kmi-region default

- rac-kmi-deploy/executor/Dockerfile
- rac-kmi-deploy/orb_version.txt
Makes it easier to run the domain tests from the CI
> Installs docker compose

- .circleci/config.yml
- .circleci/continue_config.yml
- .github/CODEOWNERS
- README.md
- oot-deploy/README.md
I missed the requirements for setting up a new orb.
This PR ensures that oot-ecr-oidc is deployed properly.
> OOT-2476 More changes to make orb live

- oot-eks-oidc/orb.yml
- oot-eks-oidc/orb_version.txt
Try another version bump to see if that fixes the issue
> OOT-2476 Try to bump orb version

- oot-eks-oidc/orb.yml
Our oidc eks orb is not quite working yet. This PR makes a few tweaks to try to fix it.
> OOT-2476 orb tweaking

- oot-eks-oidc/orb_version.txt
Forgot to bump the orb version on my recent PR.
> OOT-2476 Bump orb version

- oot-eks-oidc/orb.yml
- oot-eks-oidc/orb_version.txt
Try removing region param since it was not in our old aws-cli/setup line
> OOT-2476 Remove manually set region parameter

- oot-eks-oidc/orb.yml
- oot-eks-oidc/orb_version.txt
Try putting the arn in curly braces
> OOT-2476 more tweaks to oot-eks orb

- jaws-journey-deploy/changelog.md
- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
Adds parameter snykPolicyPath to allow for snyk exceptions to be used during container scan steps
> Add snykPolicyPath parameter

- jira/README.md
- jira/orb.yml
PR created by automated teamCPPEbot / See original pull request [here](https://github.com/ovotech/team-cppe/pull/353)
> CPPE addition / modification of CircleCI orb jira

- terraform-registry/orb.yml
- terraform-registry/orb_version.txt
> CPPE addition / modification of CircleCI orb terraform-registry

- telemetry/orb_version.txt
> CPPE addition / modification of CircleCI orb telemetry

- github-actions/orb.yml
- github-actions/orb_version.txt
> CPPE addition / modification of CircleCI orb github-actions

- build-utilities/README.md
- build-utilities/orb.yml
Added an optional argument to an underlying script
This PR is only to surface this argument to the users
> Add parameter to expose a script argument

- build-utilities/CHANGELOG.md
- build-utilities/orb_version.txt
`@ovotech` appears to have been renamed as `ovotech`
this PR is to change this and update the changelog
> Change namespace and version

- jaws-journey-deploy/changelog.md
- jaws-journey-deploy/orb.yml
- jaws-journey-deploy/orb_version.txt
This is to allow semantic release to contine working
> fix: upgrade node

- terraform-v2/CHANGELOG.md
- terraform-v2/apply.sh
- terraform-v2/orb.yml
- terraform-v2/orb_version.txt
add support for "replace" flag, so that one can replace specific targets
> add-replace-param

- rac-gcp-deploy/orb.yml
- rac-gcp-deploy/orb_version.txt
Current image is deprecated
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
> Updates base image
